<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="206184" started-at="2017-06-10T06:35:46Z" finished-at="2017-06-10T06:39:12Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="206184" started-at="2017-06-10T06:35:46Z" finished-at="2017-06-10T06:39:12Z">
      <class name="testScriptDefinitions.Module1.SampleTestScript">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testScriptDefinitions.Module1.SampleTestScript@3427b02d]" name="setUp" is-config="true" duration-ms="14" started-at="2017-06-10T12:05:48Z" finished-at="2017-06-10T12:05:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testScriptDefinitions.Module1.TC101_AddEmergencyContactsAndVerify@647e447]" name="setUp" is-config="true" duration-ms="0" started-at="2017-06-10T12:05:48Z" finished-at="2017-06-10T12:05:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testScriptDefinitions.Module1.SampleTestScript@3427b02d]" name="tearDown" is-config="true" duration-ms="1" started-at="2017-06-10T12:09:12Z" finished-at="2017-06-10T12:09:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testScriptDefinitions.Module1.TC101_AddEmergencyContactsAndVerify@647e447]" name="tearDown" is-config="true" duration-ms="0" started-at="2017-06-10T12:09:12Z" finished-at="2017-06-10T12:09:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testScriptDefinitions.Module1.SampleTestScript -->
      <class name="testScriptDefinitions.Module1.TC101_AddEmergencyContactsAndVerify">
        <test-method status="FAIL" signature="scriptDefinition()[pri:5, instance:testScriptDefinitions.Module1.TC101_AddEmergencyContactsAndVerify@647e447]" name="scriptDefinition" duration-ms="203819" started-at="2017-06-10T12:05:48Z" description="Add Emergency details and verify" finished-at="2017-06-10T12:09:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at frameworkLibrary.WebLibrary.logEvent(WebLibrary.java:1004)
	at testScriptDefinitions.Module1.TC101_AddEmergencyContactsAndVerify.scriptDefinition(TC101_AddEmergencyContactsAndVerify.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- scriptDefinition -->
      </class> <!-- testScriptDefinitions.Module1.TC101_AddEmergencyContactsAndVerify -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
